var raider = {'maneuver': {'left': [{'cardNumber': 1,
                                     'g': 0,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'cardNumber': 4,
                                     'g': 1,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'cardNumber': 2,
                                     'g': 1,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'cardNumber': 6,
                                     'g': 2,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'cardNumber': 10,
                                     'g': 3,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'cardNumber': 10,
                                     'g': 3,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'cardNumber': 12,
                                     'g': 3,
                                     'kineticEnergy': {'high': 3, 'medium': 2}}],
                           'right': [{'cardNumber': 1,
                                      'g': 0,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'cardNumber': 5,
                                      'g': 1,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'cardNumber': 3,
                                      'g': 1,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'cardNumber': 7,
                                      'g': 2,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'cardNumber': 11,
                                      'g': 3,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'cardNumber': 11,
                                      'g': 3,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'cardNumber': 13,
                                      'g': 3,
                                      'kineticEnergy': {'high': 3, 'medium': 2}}]},
              'overboost': {'left': [{'cardNumber': 14,
                                      'g': 0,
                                      'kineticEnergy': 3},
                                     {'cardNumber': 15,
                                      'g': 1,
                                      'kineticEnergy': 3},
                                     {'cardNumber': 17,
                                      'g': 2,
                                      'kineticEnergy': 3},
                                     {'cardNumber': 19,
                                      'g': 3,
                                      'kineticEnergy': 3}],
                            'right': [{'cardNumber': 14,
                                       'g': 0,
                                       'kineticEnergy': 3},
                                      {'cardNumber': 16,
                                       'g': 1,
                                       'kineticEnergy': 3},
                                      {'cardNumber': 18,
                                       'g': 2,
                                       'kineticEnergy': 3},
                                      {'cardNumber': 20,
                                       'g': 3,
                                       'kineticEnergy': 3}]}};
