var raider = {'maneuver': {'left': [{'card': 1,
                                     'g': 0,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'card': 4,
                                     'g': 1,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'card': 2,
                                     'g': 1,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'card': 6,
                                     'g': 2,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'card': 10,
                                     'g': 3,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'card': 10,
                                     'g': 3,
                                     'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                    {'card': 12,
                                     'g': 3,
                                     'kineticEnergy': {'high': 3, 'medium': 2}}],
                           'right': [{'card': 1,
                                      'g': 0,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'card': 5,
                                      'g': 1,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'card': 3,
                                      'g': 1,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'card': 7,
                                      'g': 2,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'card': 11,
                                      'g': 3,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'card': 11,
                                      'g': 3,
                                      'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                     {'card': 13,
                                      'g': 3,
                                      'kineticEnergy': {'high': 3, 'medium': 2}}]},
              'overboost': {'left': [{'card': 14,
                                      'g': 0,
                                      'kineticEnergy': 3},
                                     {'card': 15,
                                      'g': 1,
                                      'kineticEnergy': 3},
                                     {'card': 17,
                                      'g': 2,
                                      'kineticEnergy': 3},
                                     {'card': 17,
                                      'g': 2,
                                      'kineticEnergy': 3},
                                     {'card': 19,
                                      'g': 3,
                                      'kineticEnergy': 3}],
                            'right': [{'card': 14,
                                       'g': 0,
                                       'kineticEnergy': 3},
                                      {'card': 16,
                                       'g': 1,
                                       'kineticEnergy': 3},
                                      {'card': 18,
                                       'g': 2,
                                       'kineticEnergy': 3},
                                      {'card': 18,
                                       'g': 2,
                                       'kineticEnergy': 3},
                                      {'card': 20,
                                       'g': 3,
                                       'kineticEnergy': 3}]}};

var heavyRaider = {'maneuver': {'left': [{'card': 1,
                                          'g': 0,
                                          'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                         {'card': 4,
                                          'g': 1,
                                          'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                         {'card': 2,
                                          'g': 1,
                                          'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                         {'card': 6,
                                          'g': 2,
                                          'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                         {'card': 8,
                                          'g': 3,
                                          'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}}],
                                'right': [{'card': 1,
                                           'g': 0,
                                           'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                          {'card': 5,
                                           'g': 1,
                                           'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                          {'card': 3,
                                           'g': 1,
                                           'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                          {'card': 7,
                                           'g': 2,
                                           'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}},
                                          {'card': 9,
                                           'g': 3,
                                           'kineticEnergy': {'high': 3, 'medium': 2, 'low': 1}}]},
                   'overboost': {'left': [{'card': 10,
                                           'g': 0,
                                           'kineticEnergy': 3}],
                                 'right': [{'card': 10,
                                            'g': 0,
                                            'kineticEnergy': 3}]}};
